### ISSUE TITLE
OneDrive for Business Germany Support

### ISSUE THREAD

**Issue by thomas-logisch** [cryptomator/cryptomator-ios#109]
Could you please check if you can implement the support for the OneDrive Business Germany Cloud?

The URL to the graph-API is `graph.microsoft.de` instead of `graph.microsoft.com`.

But I don't know if there must be changed more than this.

Probably refering to (closed) issue #6 

Thank you!

**Comment by tobihagemann** [comment]
Thank you for your report! This is actually the first indication on how this could be solved. Found this official documentation with your tip: https://developer.microsoft.com/en-us/graph/docs/concepts/deployments

We don't have a OneDrive for Business account in "Microsoft Cloud Germany" so we can't verify this immediately. But we'll try to get a free trial somewhere so that we can do some quick tests. If you have any ideas where to get one, please let me know.

Related:
- https://community.cryptomator.org/t/how-does-the-ios-app-connect-to-one-drive/804
- https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/issues/11

**Comment by tobihagemann** [comment]
I've documented my current findings here: https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/issues/11#issuecomment-411700990

I'll do some more experiments and see if I can get any further but I hope I'll get some feedback there.

**Comment by thomas-logisch** [comment]
I don't know if it really helps but because you are cooperating with cyber/mountainduck you may probably have a look there because the newest release is able to handle the OneDrive Germany Cloud.
