### ISSUE TITLE
AWS S3 support

### ISSUE THREAD

**Issue by d0uub** [cryptomator/cryptomator-ios#110]
how to support for AWS S3 service

**Comment by notjulian** [comment]
I'm also intrested in S3 support ...

**Comment by olfway** [comment]
I wonder if plans changed and s3 support is not considered anymore?

**Comment by Ilithy** [comment]
Hello;
It's a great quality cloud service used by many users (including me), it would be handy if Cryptomator (and its Android version) supported the Amazon cloud.
Thank you for your consideration.

Respectfully

**Comment by paweljacewicz** [comment]
Hi!

2020 is almost over. Any plans for these feature to come to life? ;)

Thanks!

**Comment by olfway** [comment]
Also, aws s3 recently got strong read-after-write consistency which should simplify things

https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

**Comment by fishcharlie** [comment]
@tobihagemann Any updates on this? I'd love to start using Cryptomator, but need support for this on iOS, and specifically support for custom host/endpoint for S3.

**Comment by tobihagemann** [comment]
It's currently not on our roadmap. We're transitioning to a new project based on Swift, so that Cryptomator is fully integrated into the Files app. But the new project uses [cloud-access-swift](https://github.com/cryptomator/cloud-access-swift) and we're always happy to see open-source contributions.

**Comment by darkdragon-001** [comment]
AWS offers great [SDKs for Android/iOS](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-mobile-sdks.html) and there are tons of short tutorials available in the internet on how to get started in case anyone wants to have a look.

**Comment by fishcharlie** [comment]
@tobihagemann Awesome. One question. What is the difference between `cloud-access-swift` and `cryptolib-swift`? Would love to see what I can do in terms of submitting PRs and contributing to this project.

Looks like `cryptolib-swift` is a foundational library that handles the encryption/decryption, and can possibly be used in 3rd party apps. Then `cloud-access-swift` looks to be a way to handle FS operations with cloud providers. However that package has its own crypto stuff. I'd almost expect `cloud-access-swift` to be built on top of `cryptolib-swift` and have that as a dependency. Then this project is the client that basically handles the UI and patches everything together. That doesn't look to be the case tho. There seems to be a separation between `cloud-access-swift` and `cryptolib-swift`.

I know it's unrelated but I also created an issue for an Apple TV app request. So I'd love to possibly help improve this project and get some PRs up, while also potentially build my own custom app for Apple TV since enough of the foundation looks to be open source to achieve that.

**Comment by tobihagemann** [comment]
@fishcharlie I'd be happy to answer your question but this is getting off-topic. It would be great if you could open a new topic at https://community.cryptomator.org/ for in-depth discussions.

In short: `cloud-access-swift` is built on top of `cryptolib-swift` but only the crypto decorators (e.g., `VaultFormat7ProviderDecorator`) actually use that dependency.
