### ISSUE TITLE
Cannot share a file with Cryptomator 'Copy to Cryptomator' due to HTTP 413

### ISSUE THREAD

**Issue by fkjogu** [cryptomator/cryptomator-ios#116]
## Basic Info

I'm using iOS in version: 12.4.1

I'm running Cryptomator in version: 1.4.0 (630)

## Description

Sharing a PDF file (10 MB) in files app from iCloud to Cryptomator fails with an `HTTP 413` error.

Edit: Provided log file via email.

**Comment by tobihagemann** [comment]
It looks like you're trying to upload a large file to your Nextcloud instance. You can fix it by configuring your server, see here for some suggestions: https://github.com/nextcloud/ios/issues/396

There doesn't seem to be a standardized way for uploading chunks via WebDAV. That's why we can't fix it for "all" WebDAV instances. There are proprietary solutions ([Nextcloud actually has one](https://docs.nextcloud.com/server/stable/developer_manual/client_apis/WebDAV/chunking.html)) but we currently don't have plans to add proprietary features to our WebDAV support.
