### ISSUE TITLE
never fixed renaming bug

### ISSUE THREAD

**Issue by forestmaster** [cryptomator/cryptomator-ios#128]
Hello,

since more than one year I try to report the renaming bug that keeps being carried over in each ios version of the cryptomator app...

affects: all ios versions.
steps to reproduce:
take pictures one after another quickly on iphone 
select them in fotos app and try to share them via „save in cryptomator“

it will produce an error stating the file names need to be unique and you nees to rename EVERY SINGLE image to give them unique names.

I really hope this is fixed soon! 
just append ascending numbers to the files and done!

thank you

**Comment by tobihagemann** [comment]
Duplicate of #123, I understand that you just wanted to report the same bug again so I know that you know that it's a duplicate. 😅 

There hasn't been an update for Cryptomator for iOS for a while because we're currently transitioning to a _completely_ new app (well for users it'll just look like an update but internally it's a different app) so that Cryptomator works with the Files app. And I understand that it's quite frustrating to not see any progress even though we are making huge steps towards this new app. A release is still some months away but we're actively working on it.

Nevertheless, I'll give this issue more attention since it seems to be a regression.

**Comment by forestmaster** [comment]
Hi,
thank you for the quick answer - I know it’s a duplicate and it’s not behavior to report it again. but as you said, it’s frustrating to see that the renaming issue never got attention. 
I use the app almost exclusively to share documents (pictures) between devices and it‘s really difficult to use...

But your information helps me - if the renaming bug is fixed in the new app / update I will be very happy and will also donate again so it can stay without subscribing payment!

Thanks for the good work and the understanding,
best regards
Mathias
