### ISSUE TITLE
Can’t read HEIC on iPad other devices were good

### ISSUE THREAD

**Issue by ianianiani** [cryptomator/cryptomator-ios#143]
## Issue Checklist

Before creating a new issue make sure that you
- searched existing (and closed) issues: https://github.com/cryptomator/cryptomator-ios/issues
- searched the knowledge base: https://community.cryptomator.org/c/kb
- have read the support guide: https://github.com/cryptomator/cryptomator-ios/blob/master/SUPPORT.md
- have read the contribution guide: https://github.com/cryptomator/cryptomator-ios/blob/master/CONTRIBUTING.md
- have read the Code of Conduct: https://github.com/cryptomator/cryptomator-ios/blob/master/CODE_OF_CONDUCT.md

## Basic Info

I'm using iOS in version 14.4

I'm running Cryptomator in version:1.5.1
(You can check the version in the Cryptomator settings under "About Cryptomator".)

## Description
Can't open HEIC. Once I open HEIC app will freeze.

**Comment by tobihagemann** [comment]
I'm unable to reproduce the issue on my iPad running iOS 14.4.1. Does it happen with _all_ HEICs or just a specific one? And you mentioned that it works on other devices, did you mean other _iOS_ devices?

**Comment by ianianiani** [comment]
Yes  happen with all HEIC 
Yes it’s work well on other iOS devices

**Comment by tobihagemann** [comment]
We're using [Quick Look](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/quick-look/) to preview files, [`QLPreviewController`](https://developer.apple.com/reference/quicklook/qlpreviewcontroller) in particular. That's why it's out of our control how certain file types are displayed (except of _not_ using the capability). Since I can't even reproduce the bug, it's most likely an upstream bug. Maaaybe an iOS update will help even though iOS 14.4.1 was probably just a small security update but it's worth a try.

**Comment by ianianiani** [comment]
Yup all good now since I updated to 14.4.1 
Thx
