### ISSUE TITLE
Bug and extremly slow with WEBDAV (pCloud)

### ISSUE THREAD

**Issue by aryus96** [cryptomator/cryptomator-ios#169]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Bug and extremly slow with WEBDAV (pCloud)

### System Setup

- iOS: 15.0
- Cryptomator: 1.6.1 (760)
- pCloud 2TB

Hello,

I used to use Cryptomator with iCloud Drive (that downloads parts of the file in local cache I guess).
I switched my cloud storage to pCloud and using the WEBDAV protocol to use the cryptomator app.

Now, when I open a folder or file  it either :
- Take ~30 sec to 1min
- Send me a network error

Kind regards

### Cloud Type

WebDAV

### Steps to Reproduce

1. Open Cryptomator on IOS 
2. Configure WEBDAV connection to pCloud
3. Add the vault
4. Unlock the vault
5. Open a file or a folder

### Expected Behavior

Open quickly the file or folder

### Actual Behavior

Takes +30sec
Goes on network timeout

### Reproducibility

Always

**Comment by tobihagemann** [comment]
WebDAV performance is an issue of pCloud. However, in this particular case, it would be a valid feature request to add pCloud directly without WebDAV.

However, I noticed your bug report actually belongs to the "old" repository of the iOS app, that's why I transferred it. It would be interesting to know if you're having the same issues with the new iOS app. You can already try it out via TestFlight, see https://github.com/cryptomator/ios. But you can wait a little bit longer because we'll probably release the new app by the end of this year anyway and it's now just a matter of weeks.

The new iOS app doesn't have native pCloud support either but there is a feature request open here: https://github.com/cryptomator/cloud-access-swift/issues/3

**Comment by aryus96** [comment]
> WebDAV performance is an issue of pCloud. However, in this particular case, it would be a valid feature request to add pCloud directly without WebDAV.
> 
> However, I noticed your bug report actually belongs to the "old" repository of the iOS app, that's why I transferred it. It would be interesting to know if you're having the same issues with the new iOS app. You can already try it out via TestFlight, see https://github.com/cryptomator/ios. But you can wait a little bit longer because we'll probably release the new app by the end of this year anyway and it's now just a matter of weeks.
> 
> The new iOS app doesn't have native pCloud support either but there is a feature request open here: [cryptomator/cloud-access-swift#3](https://github.com/cryptomator/cloud-access-swift/issues/3)

I registered to the new iOS app (Cryptomator 2) with TestFlight. Unfortunately it is still very slow. I will also ask the question to pCloud regarding the speed of their WebDAV. 
It would be really great to implement pCloud natively in Cryptomator app. How long would you think this feature would take to be developed ?

**Comment by aryus96** [comment]
The issue is pcloud WEBDAV really poor performances.
I could find thread of more than 1 year old where people complains and they did nothing. Also be careful because with pcloud you cannot used WEBDAV and 2FA.
I wished I choose Icedrive.
