### ISSUE TITLE
Download and especially upload should be background tasks

### ISSUE THREAD

**Issue by MuscleRumble** [cryptomator/cryptomator-ios#3]
When the user leaves the app or locks his/her phone, downloads and uploads should proceed instead of timing out.

**Comment by MuscleRumble** [comment]
Implemented! Will be available starting with version 1.1 :smile:

**Comment by Eyremba** [comment]
@tobihagemann maybe this should be reopened. On iOS 11 (using the iPhone X), the downloads will still stop if the iPhone gets locked (for some time) or is in the background for too long.
(Around 3 to 5 minutes in the background is okay, but if it runs in the background for a few more minutes, it still cancels the upload. The same happens when you lock the phone for a too long amount of time.)
