### ISSUE TITLE
Favorite Folders as a shortcut for File Upload

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#39]
Inside a vault you could have folders/subfolders that you use regularly (more often than the root folder). When uploading a file, it would be great to have a shortcut, so that you can select these folders directly (e.g. by marking them as favorite beforehand).

**Comment by markuskreusch** [comment]
Maybe this favorite list could be build using files marked as favorite explicitly and be filled up with recently used folders if nothing (or less than X favorites) have been set.

**Comment by MuscleRumble** [comment]
Hmmm... I think we have to distinguish between "favorite folders" and "favorite files". This issue is only about "favorite folders", so that they are automatically listed in the "file upload" screen.

But it's true, we still need a separate feature request for "making files available offline (e.g. by marking them as favorite as well)". But I don't think that "favorite files" should influence "favorite folders".

**Comment by tobihagemann** [comment]
Fixed
