### ISSUE TITLE
WebDav - Error 405

### ISSUE THREAD

**Issue by markuskreusch** [cryptomator/cryptomator-ios#46]
### Basic Info

- I'm running Cryptomator on: iPhone / iPad
- I'm using Cryptomator in version: 1.1.3

### Description

With some WebDav providers vaults can not be created and files / folders can not be uploaded due to HTTP Error 405. This seems to occur due to nonstandard WebDav implementation on the server side.

Although this is an upstream problem we can not expect this to be solved on the side of the cloud provides and thus will provide a fix by accessing the servers in a different way.

This problem occurs at least when using:
- Synology DSM
- cubby.com

**Comment by MuscleRumble** [comment]
Fixed

**Comment by jaccas** [comment]
I also have same problem for my SanDisk Wireless Stick 128GB. Can't create folder when I connected by iOS Cryptomator with WebDAV

**Comment by markuskreusch** [comment]
@jaccas This problem has already been solved so I guess your problem will be a bit different. So could you please open a new issue for this and describe in detail what you do, expect and what happens?

**Comment by tobihagemann** [comment]
A new issue would be great. Could you tell us there, what worked and then what didn't work? Were you able to add the WebDAV storage to Cryptomator and just creating folder is not working? Are you able to create a folder while browsing for a target location, when creating a new vault? Are you even able to create a new vault, because that would also involve creating a new folder?

**Comment by tobihagemann** [comment]
Created new issue #75 for bug reported by @jaccas.
