### ISSUE TITLE
Cryptomator bug in iOS 10 beta 2

### ISSUE THREAD

**Issue by frankgardner15** [cryptomator/cryptomator-ios#56]
### Basic Info

- I'm running Cryptomator on: iPhone, and iPad
- I'm using Cryptomator in version: 1.1.5 (360)

### Description

When attempting to load a password-protected Pages document within the Cryptomator application, the keyboard to type in the password never appears even though the password input box is present. This occurs only on iOS 10 (currently developer beta 2) but works fine on iOS 9.

**Comment by tobihagemann** [comment]
Thanks for the report! I'm not sure if this something that's going to be fixed by Apple in future iOS 10 betas anyway, that's why I'm hesitating to look into it directly. This is going to be low priority for the next month or so, but Cryptomator will be iOS 10 ready for the final release. Thanks for the heads up!
