### ISSUE TITLE
Cooperation and Implementation in 3rd Party Apps

### ISSUE THREAD

**Issue by MajorTomDE** [cryptomator/cryptomator-ios#64]
It would be great, if you cooperate with great 3rd party apps, like Readdle ScannerPro, Readdle Documents and Doo Scanbot for a better implementation and secure sharing files. At the Moment, it's only possible with "Open with..." in iOS sharing menue - partial very uncomfortable.

A cooperation and implementation can be the change to increase the distribution and the awareness level of cryptomator.

**Comment by tobihagemann** [comment]
I believe there is no need for a direct cooperation with other apps, when we've fixed #13. At least that's what I'm hoping for, because I would prefer a "native" solution (through the capabilities of the operating system). If the open/move app extensions aren't "enough", we'll see what we can do. :smile:

Thank you for your feedback. I'll close this issue for now, because if we'd do such cooperation, we probably won't discuss this here on GitHub. :wink:
