### ISSUE TITLE
Photos with Duplicate File Names

### ISSUE THREAD

**Issue by jbrayton** [cryptomator/cryptomator-ios#78]
## Basic Info

This is a bug report.

I'm using iOS in version 10.2.1 (14D27).

I'm running Cryptomator in version 1.2.0.

## Description

When I try to upload all of my photos from my camera roll into an empty Cryptomator vault, I get this error:

> Replace File?
> A file named "[name].jpeg" already exists. Do you want to replace it?

I believe the problem is that some photos have the same timestamp down to the second. Please add a mechanism for handling multiple photos that would result in the same file name.

Thanks!

**Comment by tobihagemann** [comment]
Thank you for reporting this issue! :+1:

Looked into it and decided to fix it with version 1.2.2. We've been delaying 1.2.1 for far too long and I'd like to release it now.

I'll have to refactor the whole "upload file / check file existence / replace file" mechanism first, before I can fix this properly.

**Comment by tobihagemann** [comment]
Will be partially fixed with version 1.2.2, which is currently "waiting for review". The mentioned refactoring is still needed, because the upload mechanism isn't checking if filenames already exist on remote. It's just avoiding duplicates locally.

Example: You're trying to upload 3 files that are all called `foo.jpg`. With the fix, it'll upload `foo.jpg`, `foo (1).jpg`, and `foo (2).jpg`. However, it doesn't check beforehand if these files already exist. So if you try to upload 3 files that are all called `foo.jpg` again, they won't be called `foo (3).jpg`, `foo (4).jpg`, and `foo (5).jpg` yet.

We're going to fix it properly with a future update. I hope this is an acceptable fix for starters.

**Comment by chrisjllamb** [comment]
Hello,

On the latest version (1.4.3) I'm getting this issue again.

If I select 'Save to Cryptomator' in Photos on multiple items it will use the generation timestamp, and therefore lots of photos will have the same name and the app will complain.
