### ISSUE TITLE
WebDAV URL

### ISSUE THREAD

**Issue by wangkesen** [cryptomator/cryptomator-ios#88]
Just wondering. For the WebDAV URL that you can choose to show on OSX. What is the purpose of this? Like for example then even if I take that Url and use that in a client to upload files that doesn’t feature Cryptomator functionality, like Cyberduck, it will ask me for Username/Password but continuously denies citing incorrect credentials. Also am I correct in assuming that iOS does not have the ability to show the WebDAV URL for the vault right? My apologies for these stupid questions I’m just trying to figure out different ways of functionality, for example using Transmit on IOS to send multiple files into the vault etc, or just using Transmit on OSX to encrypt and upload files as opposed to Cyberduck since Transmit offers dual columns and is much more easier to work with that situation.

Thanks And sorry again if the questions are stupid just want to clarify that! Thanks :)

**Comment by tobihagemann** [comment]
Cryptomator on macOS provides a virtual drive via WebDAV. That means, Cryptomator technically hosts a WebDAV server so that Finder (as the WebDAV client) can connect to the server that is only accessible via localhost (so called loopback connection).

You can copy the WebDAV URL so that you can use other WebDAV clients than Finder. Cyberduck and Transmit are good examples. You have to check "Anonymous Login" (or just enter whatever you want in username/password, it doesn't matter because it's unused) in order to connect to the server.

Cryptomator on iOS works differently. It has a direct connection to the cloud storage services and emulates a file browser itself (similar to Cyberduck). In order to transfer files between Cryptomator and other apps, you'd have to use the share functionality. I'd recommend to enable the app extension (if you open up a share dialog, you can see two rows: one is colored, the other one is grey... the app extensions are the grey ones). Cryptomator's app extension hasn't unlocked its full potential yet, see #13.

No worries, I'm happy to answer your questions. 👍

**Comment by wangkesen** [comment]
Oooh okay so that’s how it works! I kept on trying the password and it was denying it haha. Thanks for that! Awesome that we can use it on any client :)
