### ISSUE TITLE
Cannot create folders with a slash "/" in it

### ISSUE THREAD

**Issue by MuscleRumble** [cryptomator/cryptomator-ios#9]
Has to be tested yet, if all cloud storage services are affected, but at least with Dropbox this leads to an error! Should either be escaped or not allowed.

**Comment by markuskreusch** [comment]
In my opinion we should disallow characters like "/", "\", ":" and maybe other characters which are known to be used as separators in paths in general. Ecaping may not be enough because different systems handle paths differently and may allow some but not all such characters. To make a vault work on all systems we can only support the subset of characters allowed on all systems.

In addition we may disallow spaces at the end and beginning of file or directory names because this causes problems on Windows.

**Comment by MuscleRumble** [comment]
Fixed by disallowing following characters: \ / : * ? " < > |

Special treatment for different OSs can be discussed in another issue for a future version.
