### ISSUE TITLE
WebDAV not compatible 

### ISSUE THREAD

**Issue by wangkesen** [cryptomator/cryptomator-ios#93]
Hey so since I updated from 1.2.3 to 1.2.4 and now on 1.2.5 I can’t open vaults anymore on WebDAV. I removed the WebDAV connection from the list to try and add it again to see if it would make any difference and now I get a prompt saying webdav isn’t compatible . I don’t know where to find the log file on iOS and I’m really worried lol.

Thanks

**Comment by tobihagemann** [comment]
Hi, could you go into some detail about your WebDAV server? If not, send us an email! :) Maybe you forgot some path to the URL? Here are the URLs of common cloud storage services: https://cryptomator.freshdesk.com/support/solutions/articles/16000047137

I know you mentioned that it worked before but we haven't changed anything in the WebDAV implementation, hm.

**Comment by wangkesen** [comment]
Hey yeah for sure. I haven’t changed anything with the WebDAV server either and able to connect fine via transmit the app, in iOS fine. The files are still there in tact from what I can gather like nothing has been deleted. It worked fine prior to the last two updates. My WebDAV is with Teracloud.jp and I haven’t changed the file paths or anything like that or modified any files. The file system they use is ZFS. It’s just now that whenever I click on any vaults associated with the WebDAV they just load for about two minutes and saying their opening but then I get that prompt that the WebDAV is not compatible. It’s definitely something on my side or with iOS tho I feel because I have a couple friends I’m sharing a vault with as well as family members and they can access the vaults fine. 

![This is the WebDAV address which hasn’t changed ](http://i.imgur.com/2fTFmq5.jpg) 

![it just gets stuck here on authenticating and then I get the WebDAV compatibility message ](http://i.imgur.com/ZaYrs7v.jpg)

**Comment by tobihagemann** [comment]
It's a complete mystery to me. But you say that it works fine on Transmit (also iOS)? Unfortunately, we don't have log files on iOS.

Some technical details on the error "Server doesn't seem to be WebDAV compatible.":

Cryptomator sends an `OPTIONS` request to the specified URL and checks if the header field `DAV` exists. If it does, Cryptomator assumes that the server is WebDAV compatible. Otherwise it throws the aforementioned error.

Reference: http://www.webdav.org/specs/rfc2518.html#HEADER_DAV

> This header indicates that the resource supports the DAV schema and protocol as specified. All DAV compliant resources must return the DAV header on all OPTIONS responses.

I just tried your URL as well and I'm getting a WebDAV-compatible response. Now I'm really puzzled by this because that would mean that you're getting a different response. But... why...

**Comment by tobihagemann** [comment]
Just a random idea: Does it change if you're connected to a Wi-Fi?

**Comment by wangkesen** [comment]
You know what like it might be that issue. We have really good 4G here but my router broke as if a couple days ago and I’ve just been using cellular but I was going to ask if that was a factor in opening the vaults actually. They’re coming to fix tmmrw so I’ll report back and see if that is actually the issue.

**Comment by wangkesen** [comment]
Cause like yeah I mean I’ve been using that storage option now for a while and 5 other users that have shared vaults with me are able to access through the same WebDAV so I figured it was an ios problem, but probably it will turn out to be the wifi issue lol.

**Comment by tobihagemann** [comment]
In an ideal world, the scenario "a client sends a request to a server and the server send a response back to the client" shouldn't make a difference between sending this request via a cellular network and via Wi-Fi (which is connected to some landline network).

My guess was that something in-between changes the request and/or response, that's why I pointed to the cellular network. If it really makes a difference when using Wi-Fi, I'd be very confused why the cellular network behaves differently. 🤔

**Comment by wangkesen** [comment]
Me too!!! Maybe Chunghwa Telecom is doing some monitoring or something any reasons that could be? Just replacing the router now will let you know how this works out

**Comment by wangkesen** [comment]
Okay so like update, I tried the connection again on cellular and the Webdav connection did authenticate but the drive wouldn’t list contents. And then when I went to open another vault it again prompted me for the WebDAV Credentials. But this is definitely something relating to cellular , perhaps it’s the speed? Does it need a certain bandwidth to pry open the vault if there’s a lot of files? Ahah ![](http://i.imgur.com/5sTPwQd.jpg)

**Comment by wangkesen** [comment]
Hey just wanted to let you know I got wifi back l, and the vaults have all opened now no problem l. Maybe I think like the cell phone speed is not enough here and perhaps the WebDAV server is timing out?

**Comment by tobihagemann** [comment]
Depending on the number of contents in a directory, speed can be a factor. Especially, if there are many files/folders with long filenames. Because then it's not just a directory listing (as it would be in "regular" unencrypted folders), it also has to download the metadata files (inside the `m` directory) in order to decrypt the long filenames.

I suppose it's okay to close this issue then. :smile: Still interesting why cellular makes such a huge difference but that's probably out of our control. What we can do is to improve performance/responsiveness via caching of directory contents. I'll keep that in mind for future versions.

**Comment by wangkesen** [comment]
Thanks la:) Most likely the shady cellular haha. Thank you very much for the help:)
